// <auto-generated />
using System;
using InkAndRealm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InkAndRealm.Server.Migrations
{
    [DbContext(typeof(DemoMapContext))]
    [Migration("20260130204716_AddPointFeatureSize")]
    partial class AddPointFeatureSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InkAndRealm.Server.Data.FeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowPointPlacement")
                        .HasColumnType("bit");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<int>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Features");

                    b.HasDiscriminator<string>("FeatureType").HasValue("FeatureEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeaturePointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("FeaturePoints");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeatureRelationshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("TargetFeatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SourceCharacterId");

                    b.HasIndex("TargetFeatureId");

                    b.ToTable("FeatureRelationships");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.MapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.MapLayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LayerIndex")
                        .HasColumnType("int");

                    b.Property<string>("LayerKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapId", "LayerIndex")
                        .IsUnique();

                    b.ToTable("MapLayers");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TownStructureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("RelativeX")
                        .HasColumnType("real");

                    b.Property<float>("RelativeY")
                        .HasColumnType("real");

                    b.Property<string>("TextureKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownFeatureId")
                        .HasColumnType("int");

                    b.Property<string>("TownStructureType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TownFeatureId");

                    b.ToTable("TownStructures");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.BridgeFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("BridgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Bridge");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.CharacterFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Character");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.HouseFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("HouseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("House");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.LandFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("ElevationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Land");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TitleFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Features", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("TitleFeatureEntity_Name");
                        });

                    b.HasDiscriminator().HasValue("Title");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TownFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("TownType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Town");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TreeFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<float>("Size")
                        .HasColumnType("real");

                    b.Property<string>("TreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Features", t =>
                        {
                            t.Property("Size")
                                .HasColumnName("TreeFeatureEntity_Size");
                        });

                    b.HasDiscriminator().HasValue("Tree");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.WaterFeatureEntity", b =>
                {
                    b.HasBaseType("InkAndRealm.Server.Data.FeatureEntity");

                    b.Property<string>("WaterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Water");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeatureEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.MapEntity", "Map")
                        .WithMany("Features")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeaturePointEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.FeatureEntity", "Feature")
                        .WithMany("Points")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeatureRelationshipEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.CharacterFeatureEntity", "SourceCharacter")
                        .WithMany("Relationships")
                        .HasForeignKey("SourceCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkAndRealm.Server.Data.FeatureEntity", "TargetFeature")
                        .WithMany()
                        .HasForeignKey("TargetFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceCharacter");

                    b.Navigation("TargetFeature");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.MapEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.UserEntity", "User")
                        .WithMany("Maps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.MapLayerEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.MapEntity", "Map")
                        .WithMany("Layers")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.SessionEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TownStructureEntity", b =>
                {
                    b.HasOne("InkAndRealm.Server.Data.TownFeatureEntity", "Town")
                        .WithMany("Structures")
                        .HasForeignKey("TownFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Town");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.FeatureEntity", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.MapEntity", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Layers");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.UserEntity", b =>
                {
                    b.Navigation("Maps");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.CharacterFeatureEntity", b =>
                {
                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("InkAndRealm.Server.Data.TownFeatureEntity", b =>
                {
                    b.Navigation("Structures");
                });
#pragma warning restore 612, 618
        }
    }
}
